In [ ]:
!ls


sample_data


In [ ]:
!pwd #! - for linux/unix

/content


****NUMPY****


To install numpy
cmd: pip install numpy

In [ ]:
import numpy as np

**ndarray**


In [ ]:
a = (1, 2, 3, 4, 5)
list(a) #tuple to list

[1, 2, 3, 4, 5]

In [ ]:
a = [1, 2, 3, 4]
a
type(a)

list

In [ ]:
a = np.array(a) #tuple or list
type(a)

numpy.ndarray

In [ ]:
print(a) #kind of matrix, 1D vector 

[1 2 3 4]


In [ ]:
a.shape 
#in numpy it is vector of either col or row not a matrix 
#output: (4,) vector of 4 elements

(4,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b = np.array([1, 3.4, 45, '345'])


In [ ]:
b.dtype

dtype('<U32')

In [ ]:
b = np.array([1, 3.4, 45, 345],'int64')

In [ ]:
b


array([  1,   3,  45, 345])

In [ ]:
b.size #no of elements

4

In [ ]:
a = np.array([1, 2, 3, 4, 5,6])
a.shape

(6,)

In [ ]:
a.reshape(4,5)

ValueError: ignored

In [ ]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#arange() # 1,2,3,4,5,6   2,4,6,     1,4,7,10 Equal difference contiguous elements can be generated

#np.arange(1,101).reshape(10,10)

np.arange(1,101,4).reshape(25,1).reshape(25,)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

Mathematical operations

In [ ]:
b = [51, 34, 45, 67, 89]
b = np.array(b)
b

array([51, 34, 45, 67, 89])

In [ ]:
c = np.arange(len(b))
c

array([0, 1, 2, 3, 4])

In [ ]:
print(b+c)

[51 35 47 70 93]


In [ ]:
d = [1, 2, 3, 4]
e = [4, 3, 2, 1]
print(d+e)

[1, 2, 3, 4, 4, 3, 2, 1]


In [ ]:
[i+j for i,j in zip(d,e)]

[5, 5, 5, 5]

In [ ]:
#scalar multiplication
pi = 3.14

b

array([51, 34, 45, 67, 89])

In [ ]:
b*pi

array([160.14, 106.76, 141.3 , 210.38, 279.46])

In [ ]:
np.add(b, c)

array([51, 35, 47, 70, 93])

In [ ]:
np.subtract(b,c)

array([51, 33, 43, 64, 85])

In [ ]:
np.multiply(b,c) #element wise

array([  0,  34,  90, 201, 356])

In [ ]:
b * c   #elemnt wise

array([  0,  34,  90, 201, 356])

In [ ]:
b@c

681

In [ ]:
np.max(b)

89

In [ ]:
np.min(b)

34

In [ ]:
b

array([51, 34, 45, 67, 89])

In [ ]:
np.average(b)

57.2

In [ ]:
c = np.arange(1,1501)
c

array([   1,    2,    3, ..., 1498, 1499, 1500])

In [ ]:
c = c.reshape(150,10)

In [ ]:
#for slicing

#array_name[row_start:row_stop, col_start:col_stop]
c[0:5, 0:5]


array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [ ]:
c[4:9, 4:6]

array([[45, 46],
       [55, 56],
       [65, 66],
       [75, 76],
       [85, 86]])

In [ ]:
c[3][3]

34

3d matrix

In [ ]:
c = c.reshape(15,10,10)

In [ ]:
c

array([[[   1,    2,    3, ...,    8,    9,   10],
        [  11,   12,   13, ...,   18,   19,   20],
        [  21,   22,   23, ...,   28,   29,   30],
        ...,
        [  71,   72,   73, ...,   78,   79,   80],
        [  81,   82,   83, ...,   88,   89,   90],
        [  91,   92,   93, ...,   98,   99,  100]],

       [[ 101,  102,  103, ...,  108,  109,  110],
        [ 111,  112,  113, ...,  118,  119,  120],
        [ 121,  122,  123, ...,  128,  129,  130],
        ...,
        [ 171,  172,  173, ...,  178,  179,  180],
        [ 181,  182,  183, ...,  188,  189,  190],
        [ 191,  192,  193, ...,  198,  199,  200]],

       [[ 201,  202,  203, ...,  208,  209,  210],
        [ 211,  212,  213, ...,  218,  219,  220],
        [ 221,  222,  223, ...,  228,  229,  230],
        ...,
        [ 271,  272,  273, ...,  278,  279,  280],
        [ 281,  282,  283, ...,  288,  289,  290],
        [ 291,  292,  293, ...,  298,  299,  300]],

       ...,

       [[1201, 1202, 120

In [ ]:
c.shape

(15, 10, 10)

In [ ]:
c = c.reshape(3,5,10,10)

In [ ]:
c

array([[[[   1,    2,    3, ...,    8,    9,   10],
         [  11,   12,   13, ...,   18,   19,   20],
         [  21,   22,   23, ...,   28,   29,   30],
         ...,
         [  71,   72,   73, ...,   78,   79,   80],
         [  81,   82,   83, ...,   88,   89,   90],
         [  91,   92,   93, ...,   98,   99,  100]],

        [[ 101,  102,  103, ...,  108,  109,  110],
         [ 111,  112,  113, ...,  118,  119,  120],
         [ 121,  122,  123, ...,  128,  129,  130],
         ...,
         [ 171,  172,  173, ...,  178,  179,  180],
         [ 181,  182,  183, ...,  188,  189,  190],
         [ 191,  192,  193, ...,  198,  199,  200]],

        [[ 201,  202,  203, ...,  208,  209,  210],
         [ 211,  212,  213, ...,  218,  219,  220],
         [ 221,  222,  223, ...,  228,  229,  230],
         ...,
         [ 271,  272,  273, ...,  278,  279,  280],
         [ 281,  282,  283, ...,  288,  289,  290],
         [ 291,  292,  293, ...,  298,  299,  300]],

        [[ 301, 

In [ ]:
c.shape

(3, 5, 10, 10)

In [ ]:
np.diagonal(c)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [ ]:
c[:12, :10]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

# Pandas


In [ ]:
# !pip install pandas
import pandas as pd
pd.__version__

'1.1.5'


dataframes ==> multidimensional (table) -> highly optimized



In [ ]:
data = {'Name': ['Chandu', 'aruna'], 'Age': [23,21]}
data
display(data)
type(data)

{'Age': [23, 21], 'Name': ['Chandu', 'aruna']}

dict

In [ ]:
data_df = pd.DataFrame(data)
display(data_df)
type(data_df)

NameError: ignored

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")


In [ ]:
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df.head(13)

longitude  latitude  ...  median_income  median_house_value
0     -114.31     34.19  ...         1.4936             66900.0
1     -114.47     34.40  ...         1.8200             80100.0
2     -114.56     33.69  ...         1.6509             85700.0
3     -114.57     33.64  ...         3.1917             73400.0
4     -114.57     33.57  ...         1.9250             65500.0
5     -114.58     33.63  ...         3.3438             74000.0
6     -114.58     33.61  ...         2.6768             82400.0
7     -114.59     34.83  ...         1.7083             48500.0
8     -114.59     33.61  ...         2.1782             58400.0
9     -114.60     34.83  ...         2.1908             48100.0
10    -114.60     33.62  ...         2.6797             86500.0
11    -114.60     33.60  ...         1.6250             62000.0
12    -114.61     34.84  ...         2.1571             48600.0

[13 rows x 9 columns]

In [ ]:
df.tail()

longitude  latitude  ...  median_income  median_house_value
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[5 rows x 9 columns]

In [ ]:
df.shape

(17000, 9)

In [ ]:
df.size

153000

In [ ]:
df.min()

longitude              -124.3500
latitude                 32.5400
housing_median_age        1.0000
total_rooms               2.0000
total_bedrooms            1.0000
population                3.0000
households                1.0000
median_income             0.4999
median_house_value    14999.0000
dtype: float64

In [ ]:
df.max()

longitude               -114.3100
latitude                  41.9500
housing_median_age        52.0000
total_rooms            37937.0000
total_bedrooms          6445.0000
population             35682.0000
households              6082.0000
median_income             15.0001
median_house_value    500001.0000
dtype: float64

In [ ]:
df.mean()

longitude               -119.562108
latitude                  35.625225
housing_median_age        28.589353
total_rooms             2643.664412
total_bedrooms           539.410824
population              1429.573941
households               501.221941
median_income              3.883578
median_house_value    207300.912353
dtype: float64

In [ ]:
df.median()


longitude               -118.4900
latitude                  34.2500
housing_median_age        29.0000
total_rooms             2127.0000
total_bedrooms           434.0000
population              1167.0000
households               409.0000
median_income              3.5446
median_house_value    180400.0000
dtype: float64

In [ ]:
df.std

<bound method DataFrame.std of        longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]>

In [ ]:
df.describe()

longitude      latitude  ...  median_income  median_house_value
count  17000.000000  17000.000000  ...   17000.000000        17000.000000
mean    -119.562108     35.625225  ...       3.883578       207300.912353
std        2.005166      2.137340  ...       1.908157       115983.764387
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.790000     33.930000  ...       2.566375       119400.000000
50%     -118.490000     34.250000  ...       3.544600       180400.000000
75%     -118.000000     37.720000  ...       4.767000       265000.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [ ]:
df.info() #strings are stored as object in python

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [ ]:
df.drop(['households'],axis=1)

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 8 columns]

In [ ]:
df

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

In [ ]:
df.drop(['households'],axis=1,inplace=True)

In [ ]:
df

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 8 columns]

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'median_income', 'median_house_value'],
      dtype='object')

In [ ]:
df.columns = [each.strip() for each in df.columns]

In [ ]:
# series
df['housing_median_age'].unique() #unique values

array([15., 19., 17., 14., 20., 29., 25., 41., 34., 46., 16., 21., 48.,
       31., 28., 24., 18., 30., 32., 23., 38., 35., 33., 13., 11., 10.,
        6., 12., 27., 22.,  5.,  8., 37.,  3., 44.,  2., 26.,  9.,  7.,
       36.,  4., 52., 40., 43., 42., 39., 49., 47., 50., 45., 51.,  1.])

In [ ]:
df['housing_median_age'].nunique() #total unique values

52

In [ ]:
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 8 columns]

pd.merge
pd.concat

In [ ]:
df['Total Rooms/Population ratio'] = df['total_rooms'] /df['population']

In [ ]:
df

longitude  latitude  ...  median_house_value  Total Rooms/Population ratio
0        -114.31     34.19  ...             66900.0                      5.529064
1        -114.47     34.40  ...             80100.0                      6.775908
2        -114.56     33.69  ...             85700.0                      2.162162
3        -114.57     33.64  ...             73400.0                      2.914563
4        -114.57     33.57  ...             65500.0                      2.330128
...          ...       ...  ...                 ...                           ...
16995    -124.26     40.58  ...            111400.0                      2.444322
16996    -124.27     40.69  ...             79000.0                      1.967337
16997    -124.30     41.84  ...            103600.0                      2.151929
16998    -124.30     41.80  ...             85800.0                      2.058552
16999    -124.35     40.54  ...             94600.0                      2.258065

[17000 rows x 9 columns]

In [ ]:
df['median_house_value'] = np.arange(1,17001)

In [ ]:
df

longitude  latitude  ...  median_house_value  Total Rooms/Population ratio
0        -114.31     34.19  ...                   1                      5.529064
1        -114.47     34.40  ...                   2                      6.775908
2        -114.56     33.69  ...                   3                      2.162162
3        -114.57     33.64  ...                   4                      2.914563
4        -114.57     33.57  ...                   5                      2.330128
...          ...       ...  ...                 ...                           ...
16995    -124.26     40.58  ...               16996                      2.444322
16996    -124.27     40.69  ...               16997                      1.967337
16997    -124.30     41.84  ...               16998                      2.151929
16998    -124.30     41.80  ...               16999                      2.058552
16999    -124.35     40.54  ...               17000                      2.258065

[17000 rows x 9 columns]

# **Boolean Masks**

In [ ]:
room_mask = df['total_rooms'] > 2000

df[room_mask]

longitude  latitude  ...  median_house_value  Total Rooms/Population ratio
0        -114.31     34.19  ...                   1                      5.529064
1        -114.47     34.40  ...                   2                      6.775908
6        -114.58     33.61  ...                   7                      1.579033
8        -114.59     33.61  ...                   9                      1.528079
10       -114.60     33.62  ...                  11                      1.536976
...          ...       ...  ...                 ...                           ...
16993    -124.23     40.54  ...               16994                      2.338542
16995    -124.26     40.58  ...               16996                      2.444322
16996    -124.27     40.69  ...               16997                      1.967337
16997    -124.30     41.84  ...               16998                      2.151929
16998    -124.30     41.80  ...               16999                      2.058552

[9242 rows x 9 columns]

In [ ]:
bed_mask = df['total_bedrooms'] >3000

In [ ]:
df[room_mask & bed_mask]

longitude  latitude  ...  median_house_value  Total Rooms/Population ratio
186      -116.33     33.75  ...                 187                      6.634375
191      -116.36     33.88  ...                 192                      5.119038
197      -116.38     33.74  ...                 198                      4.908964
420      -116.95     32.79  ...                 421                      1.586932
496      -116.99     33.73  ...                 497                      2.621854
544      -117.01     32.83  ...                 545                      2.109148
884      -117.08     32.97  ...                 885                      2.284929
1116     -117.12     33.52  ...                1117                      2.294242
1321     -117.16     33.57  ...                1322                      2.859086
1444     -117.19     33.90  ...                1445                      2.188507
1836     -117.27     33.68  ...                1837                      2.812179
1838     -117.27     33.23  ...                1839                      2.157688
1920     -117.29     33.97  ...                1921                      2.131403
2001     -117.31     33.19  ...                2002                      2.396887
2086     -117.34     33.98  ...                2087                      1.754746
2274     -117.42     33.35  ...                2275                      0.704417
2372     -117.52     33.89  ...                2373                      2.461054
2434     -117.59     34.13  ...                2435                      2.085529
2464     -117.61     34.10  ...                2465                      1.836288
2871     -117.74     33.89  ...                2872                      2.353120
2897     -117.75     34.01  ...                2898                      2.117512
2969     -117.78     34.03  ...                2970                      2.067066
3131     -117.83     33.97  ...                3132                      2.226554
3296     -117.87     34.04  ...                3297                      1.842123
3359     -117.88     33.96  ...                3360                      1.734529
4771     -118.09     34.68  ...                4772                      2.228724
4856     -118.10     34.57  ...                4857                      1.701913
6572     -118.28     34.07  ...                6573                      1.041684
7221     -118.33     33.91  ...                7222                      1.488143
7323     -118.34     33.91  ...                7324                      1.342711
7457     -118.35     33.84  ...                7458                      1.829109
7567     -118.36     33.84  ...                7568                      1.653061
7737     -118.38     33.99  ...                7738                      2.205578
8092     -118.43     34.43  ...                8093                      2.145194
8172     -118.43     33.96  ...                8173                      2.374960
8319     -118.46     34.40  ...                8320                      2.477995
8603     -118.52     34.17  ...                8604                      2.332483
8655     -118.55     34.41  ...                8656                      2.122182
8673     -118.56     34.41  ...                8674                      2.508403
8754     -118.60     34.19  ...                8755                      2.921058
8847     -118.72     34.14  ...                8848                      2.417300
8881     -118.78     34.16  ...                8882                      2.361920
8959     -118.90     34.26  ...                8960                      2.106641
10692    -120.59     34.70  ...               10693                      1.427376
11803    -121.33     38.77  ...               11804                      2.417653
11864    -121.35     38.72  ...               11865                      2.530860
11875    -121.35     38.54  ...               11876                      1.876040
12018    -121.40     38.47  ...               12019                    